services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoPSchema\SchemaCommons\Services\AllowOrDenySettingsServiceInterface:
        class: \PoPSchema\SchemaCommons\Services\AllowOrDenySettingsService

    PoPSchema\SchemaCommons\ModuleProcessors\:
        resource: '../src/ModuleProcessors/*'

    PoPSchema\SchemaCommons\FilterInputProcessors\:
        resource: '../src/FilterInputProcessors/*'

    PoPSchema\SchemaCommons\FormInputs\:
        resource: '../src/FormInputs/*'

    PoPSchema\SchemaCommons\ObjectSerializers\:
        resource: '../src/ObjectSerializers/*'

    PoPSchema\SchemaCommons\CMS\CMSHelperServiceInterface:
        class: \PoPSchema\SchemaCommons\CMS\CMSHelperService
