services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoPSchema\SchemaCommons\Services\AllowOrDenySettingsServiceInterface:
        class: \PoPSchema\SchemaCommons\Services\AllowOrDenySettingsService

    PoPSchema\SchemaCommons\ObjectSerializers\:
        resource: '../src/ObjectSerializers/*'
