services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoPCMSSchema\TagsWP\LooseContracts\:
        resource: '../src/LooseContracts/*'

    PoPCMSSchema\TagsWP\Hooks\:
        resource: '../src/Hooks/*'
    
    PoPCMSSchema\Tags\TypeAPIs\QueryableTagTypeAPIInterface:
        class: \PoPCMSSchema\TagsWP\TypeAPIs\QueryableTagTypeAPI
    
    PoPCMSSchema\Tags\TypeAPIs\UniversalTagTypeAPIInterface:
        class: \PoPCMSSchema\TagsWP\TypeAPIs\UniversalTagTypeAPI

    PoPCMSSchema\Tags\TypeAPIs\QueryableTaxonomyTagListTypeAPIInterface:
        class: \PoPCMSSchema\TagsWP\TypeAPIs\QueryableTaxonomyTagListTypeAPI
