services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoPSchema\Users\ConditionalOnComponent\CustomPosts\TypeAPIs\CustomPostUserTypeAPIInterface:
        class: \PoPSchema\UsersWP\ConditionalOnComponent\CustomPosts\TypeAPIs\CustomPostUserTypeAPI

    PoPSchema\UsersWP\ConditionalOnComponent\CustomPosts\LooseContracts\:
        resource: '../../../src/ConditionalOnComponent/CustomPosts/LooseContracts/*'

    PoPSchema\UsersWP\ConditionalOnComponent\CustomPosts\Hooks\:
        resource: '../../../src/ConditionalOnComponent/CustomPosts/Hooks/*'
