services:
    _defaults:
        public: true
        autowire: true

    PoPSchema\Comments\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPSchema\Comments\TypeResolvers\:
        resource: '../src/TypeResolvers/*'

    PoPSchema\Comments\RelationalTypeDataLoaders\:
        resource: '../src/RelationalTypeDataLoaders/*'
