services:
    _defaults:
        public: true
        autowire: true

    PoPSchema\Menus\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPSchema\Menus\TypeResolvers\:
        resource: '../src/TypeResolvers/*'

    PoPSchema\Menus\RelationalTypeDataLoaders\:
        resource: '../src/RelationalTypeDataLoaders/*'
