services:
    _defaults:
        public: true
        autowire: true

    PoPCMSSchema\PostCategories\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPCMSSchema\PostCategories\TypeResolvers\:
        resource: '../src/TypeResolvers/*'

    PoPCMSSchema\PostCategories\RelationalTypeDataLoaders\:
        resource: '../src/RelationalTypeDataLoaders/*'

    PoPCMSSchema\PostCategories\SchemaHooks\:
        resource: '../src/SchemaHooks/*'
