services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoPSchema\PostCategories\Hooks\:
        resource: '../src/Hooks/*'

    PoPSchema\PostCategories\ModuleProcessors\:
        resource: '../src/ModuleProcessors/*'
