services:
    _defaults:
        public: true
        autowire: true

    PoPCMSSchema\TaxonomyMutations\TypeResolvers\:
        resource: '../src/TypeResolvers/*'

    PoPCMSSchema\TaxonomyMutations\RelationalTypeDataLoaders\:
        resource: '../src/RelationalTypeDataLoaders/*'

    PoPCMSSchema\TaxonomyMutations\ObjectTypeResolverPickers\:
        resource: '../src/ObjectTypeResolverPickers/*'
