services:
    _defaults:
        public: true
        autowire: true

    PoPCMSSchema\UserStateMutations\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPCMSSchema\UserStateMutations\MutationResolvers\:
        resource: '../src/MutationResolvers/*'

    PoPCMSSchema\UserStateMutations\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
