services:
    _defaults:
        public: true
        autowire: true

    PoPSchema\UserStateMutations\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPSchema\UserStateMutations\MutationResolvers\:
        resource: '../src/MutationResolvers/*'

    PoPSchema\UserStateMutations\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
