services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoPSchema\Comments\Hooks\:
        resource: '../src/Hooks/*'

    PoPSchema\Comments\LooseContracts\:
        resource: '../src/LooseContracts/*'

    PoPSchema\Comments\ModuleProcessors\:
        resource: '../src/ModuleProcessors/*'

    PoPSchema\Comments\FilterInputProcessors\:
        resource: '../src/FilterInputProcessors/*'
