services:
    _defaults:
        public: true
        autowire: true

    PoPSchema\Posts\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPSchema\Posts\ObjectTypeResolverPickers\:
        resource: '../src/ObjectTypeResolverPickers/*'

    PoPSchema\Posts\TypeResolvers\:
        resource: '../src/TypeResolvers/*'

    PoPSchema\Posts\RelationalTypeDataLoaders\:
        resource: '../src/RelationalTypeDataLoaders/*'
