services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoPSchema\Tags\LooseContracts\:
        resource: '../src/LooseContracts/*'

    PoPSchema\Tags\ModuleProcessors\:
        resource: '../src/ModuleProcessors/*'

    PoPSchema\Tags\FilterInputProcessors\:
        resource: '../src/FilterInputProcessors/*'

    PoPSchema\Tags\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
