services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoPSchema\Users\Conditional\CustomPosts\TypeAPIs\CustomPostUserTypeAPIInterface:
        class: \PoPSchema\UsersWP\Conditional\CustomPosts\TypeAPIs\CustomPostUserTypeAPI

    PoPSchema\UsersWP\Conditional\CustomPosts\LooseContracts\:
        resource: '../../../src/Conditional/CustomPosts/LooseContracts/*'
