services:
    _defaults:
        public: true
        autowire: true

    GraphQLByPoP\GraphQLServer\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    GraphQLByPoP\GraphQLServer\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
