services:
    _defaults:
        public: true
        autowire: true

    PoPCMSSchema\CustomPostMutations\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPCMSSchema\CustomPostMutations\TypeResolvers\:
        resource: '../src/TypeResolvers/*'

    PoPCMSSchema\CustomPostMutations\ObjectTypeResolverPickers\:
        resource: '../src/ObjectTypeResolverPickers/*'
