services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoPSchema\Users\ConditionalOnComponent\CustomPosts\LooseContracts\:
        resource: '../../../src/ConditionalOnComponent/CustomPosts/LooseContracts/*'

    PoPSchema\Users\ConditionalOnComponent\CustomPosts\Hooks\:
        resource: '../../../src/ConditionalOnComponent/CustomPosts/Hooks/*'

    PoPSchema\Users\ConditionalOnComponent\CustomPosts\ModuleProcessors\:
        resource: '../../../src/ConditionalOnComponent/CustomPosts/ModuleProcessors/*'

    PoPSchema\Users\ConditionalOnComponent\CustomPosts\FilterInputProcessors\:
        resource: '../../../src/ConditionalOnComponent/CustomPosts/FilterInputProcessors/*'
