services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoPCMSSchema\CategoriesWP\LooseContracts\:
        resource: '../src/LooseContracts/*'

    PoPCMSSchema\CategoriesWP\Hooks\:
        resource: '../src/Hooks/*'

    PoPCMSSchema\Categories\TypeAPIs\QueryableCategoryTypeAPIInterface:
        class: \PoPCMSSchema\CategoriesWP\TypeAPIs\QueryableCategoryTypeAPI

    PoPCMSSchema\Categories\TypeAPIs\UniversalCategoryTypeAPIInterface:
        class: \PoPCMSSchema\CategoriesWP\TypeAPIs\UniversalCategoryTypeAPI

    PoPCMSSchema\Categories\TypeAPIs\InjectableTaxonomyCategoryListTypeAPIInterface:
        class: \PoPCMSSchema\CategoriesWP\TypeAPIs\InjectableTaxonomyCategoryListTypeAPI

