services:
    _defaults:
        public: true
        autowire: true

    PoPCMSSchema\CustomPosts\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPCMSSchema\CustomPosts\TypeResolvers\:
        resource: '../src/TypeResolvers/*'

    PoPCMSSchema\CustomPosts\RelationalTypeDataLoaders\:
        resource: '../src/RelationalTypeDataLoaders/*'
