services:
    _defaults:
        public: true
        autowire: true

    PoPCMSSchema\CustomPosts\TypeResolvers\UnionType\CustomPostUnionTypeResolver:
        class: \PoPCMSSchema\CustomPostsWP\Overrides\TypeResolvers\UnionType\CustomPostUnionTypeResolver

    PoPCMSSchema\CustomPosts\ObjectTypeResolverPickers\GenericCustomPostCustomPostObjectTypeResolverPicker:
        class: \PoPCMSSchema\CustomPostsWP\Overrides\ObjectTypeResolverPickers\GenericCustomPostCustomPostObjectTypeResolverPicker
