services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    persistent_cache:
        class: \PoP\Engine\Cache\Cache
        arguments:
            $cacheItemPool: '@persistent_cache_item_pool'

    memory_cache:
        class: \PoP\Engine\Cache\Cache
        arguments:
            $cacheItemPool: '@memory_cache_item_pool'

    PoP\Engine\ObjectModels\Root:
        class: \PoP\Engine\ObjectModels\Root

    PoP\Engine\Hooks\:
        resource: '../src/Hooks/*'

    PoP\Engine\LooseContracts\:
        resource: '../src/LooseContracts/*'

    PoP\Engine\FormInputs\:
        resource: '../src/FormInputs/*'

    PoP\Engine\CheckpointProcessors\:
        resource: '../src/CheckpointProcessors/*'

    PoP\Engine\ModuleFilters\:
        resource: '../src/ModuleFilters/*'

    PoP\Engine\RouteModuleProcessors\:
        resource: '../src/RouteModuleProcessors/*'

    PoP\Engine\ModuleProcessors\:
        resource: '../src/ModuleProcessors/*'

    PoP\Engine\Enums\:
        resource: '../src/Enums/*'

    PoP\Engine\TypeResolvers\:
        resource: '../src/TypeResolvers/*'

    PoP\Engine\ErrorHandling\ErrorHelperInterface:
        class: \PoP\Engine\ErrorHandling\ErrorHelper

    PoP\Engine\Schema\SchemaDefinitionServiceInterface:
        class: \PoP\Engine\Schema\SchemaDefinitionService

    PoP\Engine\Formatters\DateFormatterInterface:
        class: \PoP\Engine\Formatters\DateFormatter

    PoP\ComponentModel\Schema\SchemaDefinitionServiceInterface:
        class: \PoP\Engine\Schema\SchemaDefinitionService

    PoP\ComponentModel\EntryModule\EntryModuleManagerInterface:
        class: \PoP\Engine\EntryModule\EntryModuleManager
