services:
    _defaults:
        public: true
        autowire: true

    PoPCMSSchema\PostTagMutations\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPCMSSchema\PostTagMutations\MutationResolvers\:
        resource: '../src/MutationResolvers/*'

    PoPCMSSchema\PostTagMutations\TypeResolvers\:
        resource: '../src/TypeResolvers/*'

    PoPCMSSchema\PostTagMutations\SchemaHooks\:
        resource: '../src/SchemaHooks/*'
