services:
    _defaults:
        public: true
        autowire: true

    PoPCMSSchema\CommentMutations\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPCMSSchema\CommentMutations\MutationResolvers\:
        resource: '../src/MutationResolvers/*'

    PoPCMSSchema\CommentMutations\SchemaHooks\:
        resource: '../src/SchemaHooks/*'

    PoPCMSSchema\CommentMutations\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
