services:
    _defaults:
        public: true
        autowire: true

    PoPSchema\GenericCustomPosts\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPSchema\GenericCustomPosts\TypeResolvers\:
        resource: '../src/TypeResolvers/*'

    PoPSchema\GenericCustomPosts\RelationalTypeDataLoaders\:
        resource: '../src/RelationalTypeDataLoaders/*'
