services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoPSchema\GenericCustomPosts\ModuleProcessors\:
        resource: '../src/ModuleProcessors/*'

    PoPSchema\GenericCustomPosts\FilterInputProcessors\:
        resource: '../src/FilterInputProcessors/*'
