services:
    _defaults:
        public: true
        autowire: true

    PoPCMSSchema\MenuMutations\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPCMSSchema\MenuMutations\MutationResolvers\:
        resource: '../src/MutationResolvers/*'

    PoPCMSSchema\MenuMutations\TypeResolvers\:
        resource: '../src/TypeResolvers/*'

    PoPCMSSchema\MenuMutations\RelationalTypeDataLoaders\:
        resource: '../src/RelationalTypeDataLoaders/*'

    PoPCMSSchema\MenuMutations\ObjectTypeResolverPickers\:
        resource: '../src/ObjectTypeResolverPickers/*'
