services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoP\ConfigurationComponentModel\RouteModuleProcessors\:
        resource: '../src/RouteModuleProcessors/*'

    PoP\ConfigurationComponentModel\Hooks\:
        resource: '../src/Hooks/*'
