services:
    _defaults:
        public: true
        autowire: true

    PoPCMSSchema\CustomPosts\TypeResolvers\EnumType\CustomPostOrderByEnumTypeResolver:
        class: PoPWPSchema\CustomPosts\Overrides\TypeResolvers\EnumType\CustomPostOrderByEnumTypeResolver

    PoPCMSSchema\CustomPosts\RelationalTypeDataLoaders\ObjectType\CustomPostObjectTypeDataLoader:
        class: PoPWPSchema\CustomPosts\Overrides\RelationalTypeDataLoaders\ObjectType\CustomPostObjectTypeDataLoader
