services:
    _defaults:
        public: true
        autowire: true

    PoPSchema\Users\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPSchema\Users\TypeResolvers\:
        resource: '../src/TypeResolvers/*'

    PoPSchema\Users\RelationalTypeDataLoaders\:
        resource: '../src/RelationalTypeDataLoaders/*'
