services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoPSchema\Users\State\:
        resource: '../src/State/*'

    PoPSchema\Users\LooseContracts\:
        resource: '../src/LooseContracts/*'

    PoPSchema\Users\FilterInputProcessors\:
        resource: '../src/FilterInputProcessors/*'

    PoPSchema\Users\ModuleProcessors\:
        resource: '../src/ModuleProcessors/*'

    PoPSchema\Users\Hooks\:
        resource: '../src/Hooks/*'
