services:
    _defaults:
        public: true
        autowire: true

    PoPCMSSchema\PostTags\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPCMSSchema\PostTags\TypeResolvers\:
        resource: '../src/TypeResolvers/*'

    PoPCMSSchema\PostTags\RelationalTypeDataLoaders\:
        resource: '../src/RelationalTypeDataLoaders/*'

    PoPCMSSchema\PostTags\SchemaHooks\:
        resource: '../src/SchemaHooks/*'
