services:
    _defaults:
        public: true
        autowire: true

    PoPSchema\Media\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPSchema\Media\TypeResolvers\:
        resource: '../src/TypeResolvers/*'

    PoPSchema\Media\RelationalTypeDataLoaders\:
        resource: '../src/RelationalTypeDataLoaders/*'
