services:
    _defaults:
        public: true
        autowire: true

    PoPSchema\Users\ConditionalOnComponent\CustomPosts\FieldResolvers\:
        resource: '../../../src/ConditionalOnComponent/CustomPosts/FieldResolvers/*'

    PoPSchema\Users\ConditionalOnComponent\CustomPosts\TypeResolvers\:
        resource: '../../../src/ConditionalOnComponent/CustomPosts/TypeResolvers/*'

    PoPSchema\Users\ConditionalOnComponent\CustomPosts\SchemaHooks\:
        resource: '../../../src/ConditionalOnComponent/CustomPosts/SchemaHooks/*'
