services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoP\AccessControl\Services\AccessControlManagerInterface:
        class: \PoP\AccessControl\Services\AccessControlManager

    PoP\AccessControl\Hooks\:
        resource: '../src/Hooks/*'

    PoP\AccessControl\FeedbackItemProviders\:
        resource: '../src/FeedbackItemProviders/*'
