services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    GraphQLByPoP\GraphQLEndpointForWP\EndpointHandlers\:
        resource: '../src/EndpointHandlers/*'

    GraphQLByPoP\GraphQLEndpointForWP\State\:
        resource: '../src/State/*'
