services:
    _defaults:
        public: true
        autowire: true

    PoPSchema\CustomPostMedia\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPSchema\CustomPostMedia\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
