services:
    _defaults:
        public: true
        autowire: true

    PoPSchema\LocationPosts\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPSchema\LocationPosts\TypeResolverPickers\:
        resource: '../src/TypeResolverPickers/*'

    PoPSchema\LocationPosts\TypeResolvers\:
        resource: '../src/TypeResolvers/*'

    PoPSchema\LocationPosts\TypeDataLoaders\:
        resource: '../src/TypeDataLoaders/*'
