services:
    _defaults:
        public: true
        autowire: true

    PoPSchema\CustomPosts\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPSchema\CustomPosts\TypeResolvers\:
        resource: '../src/TypeResolvers/*'

    PoPSchema\CustomPosts\RelationalTypeDataLoaders\:
        resource: '../src/RelationalTypeDataLoaders/*'
