services:
    _defaults:
        public: true
        autowire: true

    PoP\API\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'

    PoP\API\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoP\API\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
